version: '3.3'
services:

  user-service:
    image: 'my-app/user-service:latest'
    ports:
      - '8080:8080'
    container_name: 'user-service'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - postgres
      - rabbitmq

  gambling-service:
    image: 'my-app/gambling-service:latest'
    ports:
      - '8081:8081'
    container_name: 'gambling-service'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - postgres
      - rabbitmq

  invoice-service:
    image: 'my-app/invoice-service:latest'
    ports:
      - '8082:8082'
    container_name: 'invoice-service'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - postgres
      - rabbitmq

  gateway-service:
    image: 'my-app/api-gateway-service:latest'
    ports:
      - '8083:8083'
    container_name: 'gateway-service'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
